### ISSUE TITLE
Does this rely on another shell to work?

### ISSUE THREAD

**Issue by talwat** [dustin4242/dash#1]
Basically, if you're using some king of command/exec/os library from a programming language, 90% time it already relies on another existing shell, so have you tried this without another shell installed in a container/vm/chroot?

**Comment by dustin4242** [comment]
I haven't attempted that yet, no. Once I get back from the movies I'll open a vm and see if this works

**Comment by talwat** [comment]
What movie did you watch? 👀

**Comment by dustin4242** [comment]
Cocaine bear, it was alright I suppose

**Comment by dustin4242** [comment]
Alright getting to work on chroot testing (Had multiple issues with bad isos)

P.S: I'll have to make a archiso specifically for doing these kinds of tests in the future

**Comment by dustin4242** [comment]
> Basically, if you're using some king of command/exec/os library from a programming language, 90% time it already relies on another existing shell, so have you tried this without another shell installed in a container/vm/chroot?

I can confirm now after testing in a chroot it doesn't rely on any included shells like bash, sh, zsh, etc. that are already on your system (or not)

**Comment by dustin4242** [comment]
I'll put this as closed until someone brings it up as something that isnt working properly

**Comment by talwat** [comment]
I'll test a few other distro's, but I think you're right because it  [spawns processes](https://doc.rust-lang.org/std/process/struct.Command.html) and only relies on the shell when you explicitly ask to use the shell `sh`. It makes sense for a lower level language.
